### ISSUE TITLE
No p-value filtering?

### ISSUE THREAD

**Issue by mlcossette9224** [stupornova33/parse_absREL_json#1]
Hello, 

Do you have a variation of this script that doesn't filter for p < 0.05 and basically just outputs all of the rates for each branch?

Thanks,
Marie

**Comment by stupornova33** [comment]
Hi Marie,
I have added a script to do this to my repository. You can find it here
https://github.com/stupornova33/parse_absREL_json/blob/main/parse_all_absREL_json
.

Thanks for using my script! Please cite my repository in a paper if you
find it useful for your work.

Best regards,
Taiya Jarva

**Comment by mlcossette9224** [comment]
Thank you so much, this is so helpful!

**Comment by stupornova33** [comment]
This issue has been closed.
