### ISSUE TITLE
How to interpret dNdS ratio from parsed results table?

### ISSUE THREAD

**Issue by mrmrwinter** [stupornova33/parse_absREL_json#2]
Hello,

In the output results, there is omega1, omega2, and omega3. 

Omega 3 is all NaN in my results. Omega1 ranges from 0 to 1.

How do i calculate a dNdS score for each line in the parsed output table?

Thank you.

**Comment by stupornova33** [comment]
Hi,
For a full description of the different omega values, please visit this
paper  https://doi.org/10.1093/molbev/msv022.
Basically, the aBSREL software tests for episodic positive selection at a
significant percentage of sites. It does sound by allowing multiple rates
of evolution at each branch. The omega1-3 in the output table is equivalent
to w1-3 as described in the paper. So if all of your branches in the
phylogenetic alignment have w1 <= 1 it means that all sites tested were
under negative or neutral selection. Omega3 or w3 > 1 means that there were
a significant portion of sites under positive selection.

To get one dN/dS value for a whole branch or for one site over an alignment
you would use different tests from the Hyphy suite. If I remember
correctly, MEME or BUSTED tests for selection over a whole branch. Hope
this helps.

Best,
Taiya Jarva
